version: "3"

tasks:
  generate:
    aliases:
      - migrate
    desc: "Migrations db"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path="postgres://postgres:postgres@localhost:5432/postgres_grpc?sslmode=disable" --migrations-path="./migrations" --migrations-table="custom_migrations"
